name: Build&Push Client GHCR
on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
      - '**/ci-server.yaml'
      - '**/.openshift/**'
      - '**/server/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push-ghrc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/nginx-client
          labels: |
            org.opencontainers.image.title=nginx-client
            org.opencontainers.image.description=Image based on nginx serving the web client
            org.opencontainers.image.vendor=Kounex
          tags: |
            type=ref,event=branch,priority=1000
            type=sha
            type=raw,value=latest
      - name: GHRC login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # run: |
        #   echo $GH_TOKEN | docker login ghcr.io -u Kounex --password-stdin
        # env:
        #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
